### PR TITLE
Update rust feedstock to 1.24.0

### PR DESCRIPTION
**Pull request by dlaehnemann**
* bumps up the version number
* updates sha256 hashes
* resets build number
* adds maintainer
* updates LICENSE to 2018

### CODE REVIEW

**Comment by pkgw** [comment]
Thanks! I think the Circle CI failed because of [this bug](https://github.com/conda-forge/mosfit-feedstock/issues/23#issuecomment-349112622).

**Comment by dlaehnemann** [comment]
Thanks for the quick feedback and for the useful pointer -- saved me a lot of time.

I am now trying it with the unsetting of the two variables in the `build.sh` script -- let's see if that solves it.

**Comment by dlaehnemann** [comment]
Thanks again, circle is already passing. So if Travis also passes, please feel free to merge this.

Also, a double, triple, extra thanks -- this also helped to solve the same issue with conda build in some bioconda recipes! E.g. this one:
https://github.com/bioconda/bioconda-recipes/pull/7973

**Comment by pkgw** [comment]
Thanks for submitting! Will merge if/after Travis passes.

**Pull request merged**
