### PR TITLE
Deploy aarch64 packages

### LINKED ISSUE #43: aarch64 packages built on Drone not uploaded
Appears the aarch64 packages from Drone are not being uploaded. Though I'm guessing this expected as we are still in the process of enabling Drone, correct? Anyways figured we should have somewhere to track this issue until it's resolved.

ref: https://cloud.drone.io/conda-forge/rust-feedstock/4/1/2

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #43.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Closes #43

### CODE REVIEW

**Comment by pkgw** [comment]
I will merge once CI passes unless someone tells me not to!

**Comment by pkgw** [comment]
Closes #43.

I think.

**Comment by jakirkham** [comment]
Yes, please do! This should deploy the aarch64 packages. 😄

**Comment by jakirkham** [comment]
> Closes #43.
> 
> I think.

Thanks added to the OP 👍

**Comment by jakirkham** [comment]
CI passes! 🎉 😄

**Comment by jakirkham** [comment]
Yep, that fixed thanks @pkgw and @isuruf! 😄

**Pull request merged**
