### PR TITLE
Use binary distribution of rust.

### PR DESCRIPTION
**Pull request by johanneskoester**
I hope to use this as a workaround until rust-lang/rust#43311 is fixed.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Just curious... What are the reason to go for the binaries? (We strive to do the opposite!)

**Comment by johanneskoester** [comment]
The reason is this bug: rust-lang/rust#43311

**Comment by ocefpaf** [comment]
> The reason is this bug: rust-lang/rust#43311

Thanks @johanneskoester! Let is open an issue later and xref to rust-lang/rust#4331 so we can keep track of this.

**Comment by johanneskoester** [comment]
Yes.

**Comment by johanneskoester** [comment]
@jbaaijens is have solved the issue using the binary distribution of Rust. You should be able to build your package in about half an hour.

**Comment by jbaaijens** [comment]
Thanks @johanneskoester, it works!

**Pull request merged**
