### PR TITLE
Add a dev label for nightly releases

### LINKED ISSUE #31: Add rust unstable with the dev label
While the ability to install rust with conda is quite nice, something I have found limiting so far is the ability to install rust unstable needed for some packages/crates. 

As far as I understood, features currently in rust unstable have no guarantee of making into the stable, and so when those are needed by a crate, waiting for the next release of rust is not a viable solution.

In particular, rust unstable is currently required by https://github.com/PyO3/pyo3 (bindings for CPython C API) and as a result https://github.com/rust-numpy/rust-numpy (binding for numpy C API). Given the amount of Python package on conda-forge, I think it is quite important to be able to build a Python package with a "C" extension written in Rust.

If you think it's a good idea, I can (try) to make a PR to add rust unstable under e.g. [`dev` label](https://anaconda.org/conda-forge/repo?label=dev) (or some other non-default label).

### PR DESCRIPTION
**Pull request by andfoy**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #31

This PR enables conda-forge to build nightly versions of Rust, however, this PR must be merged against a new branch ``dev`` according to [CFEP-05](https://github.com/conda-forge/cfep/blob/master/cfep-05.md). I would appreciate if any @conda-forge/rust maintainers could help creating that branch

### CODE REVIEW

**Comment by pkgw** [comment]
Thanks for tackling this. Updates to the dev branch would have to occur manually, correct?

I don't suppose there's a way to point to date-coded nightly tarballs, is there? The builds are failing because the cryptographic digests of the tarballs have changed, which is going to be a perennial annoyance (but not a showstopper) if we have to point to ever-changing `rust-nightly-*` tarballs.

**Comment by andfoy** [comment]
> I don't suppose there's a way to point to date-coded nightly tarballs, is there? The builds are failing because the cryptographic digests of the tarballs have changed, which is going to be a perennial annoyance (but not a showstopper) if we have to point to ever-changing rust-nightly-* tarballs.

We could download date-specific tarballs using the specific URLs pinpointed by https://github.com/rust-lang/rust-forge/blob/master/src/infra/channel-layout.md

**Comment by andfoy** [comment]
I could do that, if you agree

**Comment by andfoy** [comment]
> Thanks for tackling this. Updates to the dev branch would have to occur manually, correct?

I think so

**Comment by pkgw** [comment]
@andfoy If the date-specific tarballs don't mess up any other aspects of the build pipeline, I think it would be much better to point the feedstock at them.

Relatedly, can we munge the nightly date code into the package build field so that people can easily see which version they're using?

**Comment by andfoy** [comment]
> @andfoy If the date-specific tarballs don't mess up any other aspects of the build pipeline, I think it would be much better to point the feedstock at them.

Sure! I'll update the recipe to point to the nightly of today

> Relatedly, can we munge the nightly date code into the package build field so that people can easily see which version they're using?

I think we can set the version to highlight the date, let me see more about in the conda-forge documentation

**Comment by andfoy** [comment]
I think we could encode the date as ``<rust_version>``. ``dev`` ``year`` ``month`` ``day``

**Comment by andfoy** [comment]
@pkgw I think that the versioning did work indeed

**Comment by pkgw** [comment]
I have created a new `dev` branch equal to this branch, added a rerender commit, and retargeted this PR against the new branch. We can merge once CI passes.

**Comment by andfoy** [comment]
Thanks! @pkgw

**Pull request merged**
