### PR TITLE
Debug main, do we see the same failure?

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Same failure here :(

**Comment by xhochy** [comment]
@jaimergp I think I found a bug in `conda-libmamba-solver=24.7.0`, but I don't know how I can provide more useful information. The `rust` package on `osx-*` is simply not found in the testing phase. The only diff I can find that remotely has to do with this is https://github.com/conda/conda-libmamba-solver/pull/485

**Comment by mbargull** [comment]
Could be virtual package handling, but could also be caching related, i.e., https://github.com/conda/conda-libmamba-solver/pull/482 .

**Comment by pkgw** [comment]
@xhochy Nice investigation! Thanks for digging into this.

**Comment by jaimergp** [comment]
Thanks for the report. Is it ok if I debug things in your branch directly? Thinking of creating a couple of conda-libmamba-solver branches with a couple reverts to see which one is the culprit.

**Comment by jaimergp** [comment]
> Could be virtual package handling, but could also be caching related, i.e., [conda/conda-libmamba-solver#482](https://github.com/conda/conda-libmamba-solver/pull/482) .

We are supposedly [not using .solv files during channel reloads](https://github.com/conda/conda-libmamba-solver/blob/d3a1f5097ec83592b1573dfa9e86ca4da335ee93/conda_libmamba_solver/index.py#L175) but maybe there's a bug in that logic too 😬

**Comment by xhochy** [comment]
> Thanks for the report. Is it ok if I debug things in your branch directly? Thinking of creating a couple of conda-libmamba-solver branches with a couple reverts to see which one is the culprit.

Yes, feel free to push freely here.

**Comment by jaimergp** [comment]
Trying https://github.com/conda/conda-libmamba-solver/commit/8ed96893a74ea73602d93bf52b07e6ab91c7c9b0, no solv files at all.

**Comment by jaimergp** [comment]
That didn't change much. Trying https://github.com/conda/conda-libmamba-solver/commit/610422c2ca1baa2bb1db630dc6e788ee0b28f72e, which brings https://github.com/conda/conda-libmamba-solver/pull/485 back.

**Comment by jaimergp** [comment]
Well, same story. I really wonder if this is it? https://github.com/conda/conda-libmamba-solver/commit/63c545ff18bab917efd767bd209c4fbcf886063f

**Comment by jaimergp** [comment]
No way 😂 Why!

**Comment by jaimergp** [comment]
Let's see what the difference is with deduplicated channels or not. I suspect there's some bug in the `Channel` object in conda, where the "identity" of the channel might not consider the subdir or something like that, so it gets deduped, but wrongly so.

**Comment by jaimergp** [comment]
The list of channels (and their URLs) are indeed identical, so I'm clueless why deduplication affects the reloading. My guess is that there might be some sort of race condition when they are reloaded rapidly in succession, so loading them twice in a row would help with the Python objects getting updated. I've added a `sleep(1)` statement to see if that helps.

**Comment by jaimergp** [comment]
Ah wait, in one of the cases we see this: 

```
file:///Users/runner/miniforge3/conda-bld/noarch
 > file:///Users/runner/miniforge3/conda-bld/noarch
file:///Users/runner/miniforge3/conda-bld/osx-64
 > file:///Users/runner/miniforge3/conda-bld/osx-64
 > file:///Users/runner/miniforge3/conda-bld/noarch
https://conda.anaconda.org/conda-forge/osx-64
 > https://conda.anaconda.org/conda-forge/osx-64
 > https://conda.anaconda.org/conda-forge/noarch
---
file:///Users/runner/miniforge3/conda-bld/noarch
 > file:///Users/runner/miniforge3/conda-bld/noarch
https://conda.anaconda.org/conda-forge/osx-64
 > https://conda.anaconda.org/conda-forge/osx-64
 > https://conda.anaconda.org/conda-forge/noarch
```

The osx-64 subdir is missing in the first channel (but not in the second), so it gets lost after deduplication. I think deduplication should be done on URLs not Channels. And this is done internally with explicit subdirs, BUT turns out that `Channel.urls()` silently ignores the `subdirs` keyword if `Channel.platform` is defined. Great.

**Comment by jaimergp** [comment]
Published https://github.com/conda/conda-libmamba-solver/pull/531 which will be released with 24.9.

**Comment by pkgw** [comment]
Thanks for hunting this down @jaimergp!

**Comment by jaimergp** [comment]
Thanks for the reports! I think we can close this one, right? `main` is working after all. Once 24.9 we can revert the conda-forge.yml changes.

**Comment by xhochy** [comment]
Thank you for the effort 😍

**Pull request closed without merging**
