### PR TITLE
Add additional test case.

### PR DESCRIPTION
**Pull request by johanneskoester**
Add tests that reveals issues we have when using this package to compile rust programs.

### CODE REVIEW

**Comment by johanneskoester** [comment]
Ok, the test case indeed captures the problem. Now lets debug.

**Comment by johanneskoester** [comment]
@jbaaijens I can reproduce the problem with any rust package. Let's see if downgrading llvmdev helps.

**Comment by jakirkham** [comment]
FYI please remember to fork in the future. :)

**Comment by johanneskoester** [comment]
Ok @jakirkham, sorry!

**Comment by jakirkham** [comment]
Noticed one of the commits mentioned speeding up the build. Have you tried [Ninja]( https://ninja-build.org )?

**Comment by jakirkham** [comment]
Also might be worth using [ccache]( https://ccache.samba.org/ ) as well.

**Comment by johanneskoester** [comment]
Probably yes. I am about to use the prebuilt binaries though, at least until my issue on the rust side is solved.

**Comment by johanneskoester** [comment]
Closed in favor of #2 (as a workaround until the issue in rustc is solved. Also see issue #3.

**Pull request closed without merging**
