### PR TITLE
Update rust nightly to 1.53.0 2021-03-24

### PR DESCRIPTION
**Pull request by alippai**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by alippai** [comment]
It's almost good, one CI job timed out while running actively.

**Comment by pkgw** [comment]
Oh, will this branch of the feedstock need to port in the "performance" work done on the main branch, which gets the installer script running quicker? Cf. #75.

**Comment by alippai** [comment]
@pkgw does this mean that more work is needed before this gets merged?

**Comment by pkgw** [comment]
@alippai It would mean that someone would need to take the support work that's been done on `master` and merge it into this branch. Nothing too complex, but I can do it if you're unable to.

**Comment by alippai** [comment]
Looks like it's more than a simple rebase or copy-paste. I know zero about (cross)compiling and only a little about conda / Azure. I don't think I can make it with reasonable effort (and equal help) at this moment

**Comment by pkgw** [comment]
OK, I've merged `master` into this PR and hopefully done all of the conflict resolution correctly.

**Comment by pkgw** [comment]
@conda-forge/rust Anyone mind checking my work? This basically takes `master`, rerenders, and updates the head of `meta.yaml` to update the nightly version(s) and digests.

**Comment by alippai** [comment]
Friendly bump

**Comment by pkgw** [comment]
Thanks for the reminder!

**Comment by alippai** [comment]
@pkgw I don't think this succeeded. Channel `conda-forge/label/rust_dev rust` still resolves to `1.49.0.dev20201015-hd18ef5c_0`.

**Comment by alippai** [comment]
Should https://github.com/conda-forge/rust-feedstock/blob/dev/.ci_support/linux_64_.yaml say channel target rust_dev?

**Pull request merged**
