### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #41.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by pkgw** [comment]
@isuruf Err, is this right? It deleted the `.drone.yml` and various other files ...

**Comment by isuruf** [comment]
There's a conflict at https://github.com/conda-forge/rust-feedstock/blob/master/conda-forge.yml#L6 and https://github.com/conda-forge/rust-feedstock/blob/master/conda-forge.yml#L9

**Comment by pkgw** [comment]
Thanks for the sharp eye and quick analysis! Now the diff looks reasonable — AppVeyor goes away, Azure/Windows becomes set to upload packages.

**Comment by pkgw** [comment]
@isuruf Sorry for the many questions, but: does this need a build number bump? (If the Windows change is even the intended point of this rerender?)

**Comment by isuruf** [comment]
It doesn't. In the other PR, I meant merge master into PR branch and rerender. Not merge PR branch into master and rerender. But that's fine now.

**Pull request merged**
