### PR TITLE
Add iOS targets to the feedstock

### PR DESCRIPTION
**Pull request by brizental**
Hi folks! I work over at the [Mozilla VPN project](https://github.com/mozilla-mobile/mozilla-vpn-client) and we started to use conda recently. In order to build our application for iOS we need to add this targets to the feedstock.

I would be happy to help out as a maintainer on this feedstock to support the new targets if necessary (we will soon also need to add Android targets as well). Let me know, thanks!

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by brizental** [comment]
Alright folks, you may have already noticed this at this point, but I have very little conda experience. If I understand correctly there are no iOS [preprocessing selectors](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#id17) for iOS. Anyways, I'll just close this one and if we realize it is actually possible I'll come back :D

**Comment by isuruf** [comment]
We can't provide the compiler for those platforms, since don't support them, but we could provide `rust-std` package for those if there's enough interest.

**Comment by birdsarah** [comment]
Hi @isuruf! Thanks for getting in touch.

I work with @brizental who is hopefully enjoying her vacation this week and not checking github :)

To be clear about what we're looking for, in our usecase, it's the target that you get when you, for example, do `rustup target add aarch64-linux-android`. 

Then on windows, mac or linux machines we can run a rust compile action with a cross compilation target.

**Comment by birdsarah** [comment]
Having read a bit more today I believe that what I described is, as you said, getting the `rust-std` package.

**Pull request closed without merging**
