### PR TITLE
rust 1.21.0

### PR DESCRIPTION
**Pull request by abhi18av**
Bringing the rust feedstock up to date

### CODE REVIEW

**Comment by pkgw** [comment]
@johanneskoester Is this merge-able?

**Comment by abhi18av** [comment]
@johanneskoester and **conda rust-feedstock** team - guys, could you help me out here :)

**Comment by pkgw** [comment]
@ocefpaf @jakirkham We're having trouble flagging down the maintainer here. In my opinion this PR is a no-brainer, as it were — can admins merge independently?

**Comment by jakirkham** [comment]
Sure. This seems fine.

Though I would encourage one or both of you to add yourselves as maintainers so that you can proceed with changes here in a smoother manner in the future. Sound reasonable?

**Comment by pkgw** [comment]
I am totally happy to be a maintainer, although I definitely don't want to step on @johanneskoester's toes either. I'll submit a PR with that change, and if we still have trouble flagging down @johanneskoester in a week or two, maybe we can go ahead and merge it too.

**Comment by pkgw** [comment]
Oh, I didn't notice that this commit added @abhi18av as a maintainer already. Well, I'll still submit that PR.

**Comment by jakirkham** [comment]
Yeah, I saw that after I posted the comment.

IDK. We had a contributor submit `lua` and then they changed jobs and that feedstock went unmaintained for many months, which made it harder for people still interested to use it and fix it. Would rather not have that happen with `rust`. If there are able hands interested in maintaining this feedstock, let's on-board them is what I think. 😄 After all interpreters and compilers have much greater utility. So it is reasonable to have many maintainers on them to keep them operational.

**Comment by jakirkham** [comment]
FYI @abhi18av, you should have gotten an invitation to join conda-forge. If you accept that, permissions to this and your other feedstocks should be conferred. Please let me know if you have any issues.

**Comment by abhi18av** [comment]
@jakirkham @pkgw Yeah I'd love to be a maintainer of this feedstock and a few more I've been working on.

I really do believe that conda-feedstocks would solve so many issues I have while development.  I'm genuine pushing for this wonderful tool and channel in my organization and my own workflow.

@jakirkham I haven't received any invitation so far.

**Comment by jakirkham** [comment]
So should have come in an email from GitHub. Alternatively navigate to the org webpage and look at the top near the banner.

**Comment by abhi18av** [comment]
@jakirkham yup, this is resolved now :+1:

**Pull request merged**
