### PR TITLE
Start on nightly update to latest

### PR DESCRIPTION
**Pull request by timkpaine**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by timkpaine** [comment]
@conda-forge-admin, please rerender

**Comment by timkpaine** [comment]
will need to fetch the new hashes

**Comment by timkpaine** [comment]
https://github.com/conda-forge/polars-feedstock/pull/37

**Comment by ghuls** [comment]
It might be worth to add this helper function to easily get the new hashes:
```bash
get_sha256sum_rust_nightly () {
    local year=${1};
    local month=${2};
    local day=${3};
    
    # [linux and x86_64]
    curl "https://static.rust-lang.org/dist/${year}-${month}-${day}/rust-nightly-x86_64-unknown-linux-gnu.tar.gz.sha256";
    # [aarch64]
    curl "https://static.rust-lang.org/dist/${year}-${month}-${day}/rust-nightly-aarch64-unknown-linux-gnu.tar.gz.sha256";
    # [ppc64le]
    curl "https://static.rust-lang.org/dist/${year}-${month}-${day}/rust-nightly-powerpc64le-unknown-linux-gnu.tar.gz.sha256";
    # [osx and x86_64]
    curl "https://static.rust-lang.org/dist/${year}-${month}-${day}/rust-nightly-x86_64-apple-darwin.tar.gz.sha256";
    # [osx and arm64]
    curl "https://static.rust-lang.org/dist/${year}-${month}-${day}/rust-nightly-aarch64-apple-darwin.tar.gz.sha256";
    # [win64]
    curl "https://static.rust-lang.org/dist/${year}-${month}-${day}/rust-nightly-x86_64-pc-windows-msvc.tar.gz.sha256";
}
```

```
❯ get_sha256sum_rust_nightly 2022 08 19
8a6480a7e36a4692a381d9662053a534d3d2331833517b1151b6fe26434ecfd2  rust-nightly-x86_64-unknown-linux-gnu.tar.gz
ff0bcab46b8e433a9fd76fd8e7251693f5a589cdf68ecdc61a29419f5e0b3556  rust-nightly-aarch64-unknown-linux-gnu.tar.gz
80985d43d5733a5780bc37c1e89f207e49bac62b0ca13f203f7616b62cb6001f  rust-nightly-powerpc64le-unknown-linux-gnu.tar.gz
f555e8c5ae034ead5c3ae719cf584cb1d20ec39f3fc8db243c3564ee7f8f80aa  rust-nightly-x86_64-apple-darwin.tar.gz
fc82c97d7a614ad823f1ba2fce81ef77aeb578be431f02619fc6146f6b35f4e8  rust-nightly-aarch64-apple-darwin.tar.gz
2450a40e4f3472f80d30da019b94422375f79d2b0aadbe2c79717172cf67aeb7  rust-nightly-x86_64-pc-windows-msvc.tar.gz
```

**Comment by timkpaine** [comment]
> It might be worth to add this helper function to easily get the new hashes:
> 
> ```shell
> get_sha256sum_rust_nightly () {
>     local year=${1};
>     local month=${2};
>     local day=${3};
>     
>     # [linux and x86_64]
>     curl "https://static.rust-lang.org/dist/${year}-${month}-${day}/rust-nightly-x86_64-unknown-linux-gnu.tar.gz.sha256";
>     # [aarch64]
>     curl "https://static.rust-lang.org/dist/${year}-${month}-${day}/rust-nightly-aarch64-unknown-linux-gnu.tar.gz.sha256";
>     # [ppc64le]
>     curl "https://static.rust-lang.org/dist/${year}-${month}-${day}/rust-nightly-powerpc64le-unknown-linux-gnu.tar.gz.sha256";
>     # [osx and x86_64]
>     curl "https://static.rust-lang.org/dist/${year}-${month}-${day}/rust-nightly-x86_64-apple-darwin.tar.gz.sha256";
>     # [osx and arm64]
>     curl "https://static.rust-lang.org/dist/${year}-${month}-${day}/rust-nightly-aarch64-apple-darwin.tar.gz.sha256";
>     # [win64]
>     curl "https://static.rust-lang.org/dist/${year}-${month}-${day}/rust-nightly-x86_64-pc-windows-msvc.tar.gz.sha256";
> }
> ```
> 
>  ```
> ❯ get_sha256sum_rust_nightly 2022 08 19
> 8a6480a7e36a4692a381d9662053a534d3d2331833517b1151b6fe26434ecfd2  rust-nightly-x86_64-unknown-linux-gnu.tar.gz
> ff0bcab46b8e433a9fd76fd8e7251693f5a589cdf68ecdc61a29419f5e0b3556  rust-nightly-aarch64-unknown-linux-gnu.tar.gz
> 80985d43d5733a5780bc37c1e89f207e49bac62b0ca13f203f7616b62cb6001f  rust-nightly-powerpc64le-unknown-linux-gnu.tar.gz
> f555e8c5ae034ead5c3ae719cf584cb1d20ec39f3fc8db243c3564ee7f8f80aa  rust-nightly-x86_64-apple-darwin.tar.gz
> fc82c97d7a614ad823f1ba2fce81ef77aeb578be431f02619fc6146f6b35f4e8  rust-nightly-aarch64-apple-darwin.tar.gz
> 2450a40e4f3472f80d30da019b94422375f79d2b0aadbe2c79717172cf67aeb7  rust-nightly-x86_64-pc-windows-msvc.tar.gz
> ```

Thanks will brainstorm where to put this, at the very least can just put it in a helper script in the repo

**Comment by ghuls** [comment]
Can this be merged so polars-feedstock can be finally build?

**Comment by isuruf** [comment]
> It might be worth to add this helper function to easily get the new hashes:

There's one already in https://github.com/conda-forge/rust-feedstock/blob/9b310c514a0c61d9f9dfa22feaab192236d114b3/recipe/update-sha.sh

**Comment by ghuls** [comment]
> > It might be worth to add this helper function to easily get the new hashes:
> 
> There's one already in https://github.com/conda-forge/rust-feedstock/blob/9b310c514a0c61d9f9dfa22feaab192236d114b3/recipe/update-sha.sh

Seems weird to require to download the full archives to just get the sha256sum, when a dedicated sha256 txt file is available.

**Comment by timkpaine** [comment]
> > > It might be worth to add this helper function to easily get the new hashes:
> > 
> > 
> > There's one already in https://github.com/conda-forge/rust-feedstock/blob/9b310c514a0c61d9f9dfa22feaab192236d114b3/recipe/update-sha.sh
> 
> Seems weird to require to download the full archives to just get the sha256sum, when a dedicated sha256 txt file is available.

Yeah I think this is useful in a helper script so maintainers can easily use it when updating. I've been making modifications from my phone but when I get back to a computer I will clean it up and add it as a command line tool, for now we can merge this PR as is.

**Comment by ghuls** [comment]
@timkpaine Could the pr be updated to nightly-2022-08-22 (version needed by latest polars).

**Comment by timkpaine** [comment]
Yep can do

**Comment by xhochy** [comment]
Merging and we can do a new PR for the new version (will do this immediately).

**Comment by timkpaine** [comment]
https://github.com/conda-forge/rust-feedstock/pull/117

**Comment by ghuls** [comment]
when building polars-feedstock, it can't find this nightly as it looks for `"rust_linux-64=1.65.0.dev20220819")`
```
  File "/opt/conda/lib/python3.9/site-packages/conda_build/render.py", line 373, in _read_upstream_pin_files
    deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/render.py", line 138, in get_env_dependencies
    actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 133, in mamba_get_install_actions
    raise err
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("rust_linux-64=1.65.0.dev20220819")}
Traceback (most recent call last):
  File "./build-locally.py", line 105, in <module>
    main()
  File "./build-locally.py", line 93, in main
    run_docker_build(ns)
  File "./build-locally.py", line 29, in run_docker_build
    subprocess.check_call([script])
  File "/home/ghuls/software/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.

```

Why does it not search for `'rust[subdir=linux-64]=1.65.0.dev20220819'` instead?

```bash
❯ conda search -c conda-forge/label/rust_dev 'rust*=1.65.0.dev20220819'
Loading channels: done
# Name                       Version           Build  Channel             
rust                 1.65.0.dev20220819      hd7db84c_0  conda-forge/label/rust_dev
rust-std-aarch64-apple-darwin 1.65.0.dev20220819      h317b3fe_0  conda-forge/label/rust_dev
rust-std-aarch64-unknown-linux-gnu 1.65.0.dev20220819      h3b32ecd_0  conda-forge/label/rust_dev
rust-std-powerpc64le-unknown-linux-gnu 1.65.0.dev20220819      h5e365cc_0  conda-forge/label/rust_dev
rust-std-x86_64-apple-darwin 1.65.0.dev20220819      h609d47a_0  conda-forge/label/rust_dev
rust-std-x86_64-pc-windows-msvc 1.65.0.dev20220819      h059f928_0  conda-forge/label/rust_dev
rust-std-x86_64-unknown-linux-gnu 1.65.0.dev20220819      h6134ef6_0  conda-forge/label/rust_dev

❯ conda search -c conda-forge/label/rust_dev 'rust[subdir=linux-64]=1.65.0.dev20220819'
Loading channels: done
# Name                       Version           Build  Channel             
rust                 1.65.0.dev20220819      hd7db84c_0  conda-forge/label/rust_dev

```

**Comment by isuruf** [comment]
`rust=1.65.0.dev20220819` and `rust_linus-64=1.65.0.dev20220819 ` are two different things. Former exists and the latter doesn't.

**Comment by ghuls** [comment]
Should something else be used than: `{{ compiler('rust') }}`, as that one seems to cause the issue? 
```
❯ cat conda_build_config.yaml 
c_compiler:  # [win]
  - vs2019  # [win]

rust_compiler:
  - rust
rust_compiler_version:
  - 1.65.0.dev20220819

channel_sources:
  - conda-forge/label/rust_dev,conda-forge
channel_targets:
  - conda-forge main

```

**meta.yaml**:
```
...
requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - posix                               # [win]
    - cmake
    - make                                # [unix]
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=0.13,<0.14
  run:
    - python
    - numpy >=1.16.0
    - typing_extensions >=4.0.0            # [py<310]

...
```

**Comment by isuruf** [comment]
See https://github.com/conda-forge/polars-feedstock/pull/37#issuecomment-1220808498 on how to do this

**Pull request merged**
